Repository Qiskit/qiskit-code-assistant-jupyterlab, pull requests merged in 2024-09, with the labels that each got.

#2 Address dependabot and github action failures
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  README-PyPi.md
  qiskit_code_assistant_jupyterlab/handlers.py
  yarn.lock
Labels: bug

#4 Add End User License Agreement for Qiskit Code Assistant
  README-PyPi.md
  README.md
  docs/EULA.md
  package.json
Labels: enhancement

#5 Aligning descriptions with the VSCode extension
  README-PyPi.md
  README.md
  package.json
Labels: documentation, enhancement
