Repository Qiskit/qiskit-code-assistant-jupyterlab, pull requests merged in 2024-10, with the labels that each got.

#8 highlight note about nodejs in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#12 Updating the Qiskit Code Assistant references in the EULA
  docs/EULA.md
Labels: documentation, enhancement

#13 Update to Jupyterlab 4.3 and fix prompt accept bug
  GETTING_STARTED.md
  README.md
  package.json
  pyproject.toml
  src/QiskitCompletionProvider.ts
  src/index.ts
  yarn.lock
Labels: bug
